version: '3.8'

services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: zapier-db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  queue:
    image: apache/kafka:3.9.0
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - kafka_data:/var/lib/kafka/data

volumes:
  db_data:
  kafka_data: